name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: xcodebuild test -scheme AsyncOperation-Package -destination platform="macOS" -enableCodeCoverage YES
    - name: Export test results
      run: xcrun llvm-cov export -format="lcov" .build/debug/AsyncOperationPackageTests.xctest/Contents/MacOS/AsyncOperationPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Codecov
      uses: codecov/codecov-action@v1.3.1
      with:
        fail_ci_if_error: true
        verbose: true
        xcode_package: -J '^AsyncOperation$'
